name: Build and Release
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  tags:
    - 'v*'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: Install dependencies
        run: |
          rustup target add aarch64-apple-darwin
          rustup target add x86_64-apple-darwin
      
      - name: Build
        run: |
          cd src-tauri
          cargo build --release

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: Install dependencies
        run: |
          rustup target add aarch64-apple-darwin
          rustup target add x86_64-apple-darwin
      
      - name: Build Release
        run: |
          cd src-tauri
          cargo tauri build
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            src-tauri/target/release/bundle/macos/*.app
            src-tauri/target/release/bundle/dmg/*.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 